computers/urls.py
from django.urls import path, include

from . import views

app_name = "com"

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("logs/", views.Logs.as_view(), name="logs"),
    path("logs/<int:pk>", views.LogDetail.as_view(), name="log_detail"),

    path("computers/", views.Computers.as_view(), name="computers"),
    path("computers/<int:pk>", views.ComputerDetail.as_view(), name="computer"),

    path("branches/", views.Branches.as_view(), name="branches"),
    path("branches/<int:pk>", views.BranchDetail.as_view(), name="branch_detail"),

    path("reports/", views.Reports.as_view(), name="reps"),
    path("events/", views.Events.as_view(), name="events"),
    path("events/<int:pk>/", views.EventDetail.as_view(), name="event"),

    path("change-password/", views.ChangePwd.as_view(), name="change_password"),
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
]

mmc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('computers.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/branch.html
{% extends 'base.html' %}
{% load humanize %}
{% block branches_link_active %}active{% endblock %}
{% block page_header_title %}Branch #{{br.id}} &mdash; {{br.name}}{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>Branch ID</th>
                                <th>Name</th>
                                <th>Created On</th>
                                <th>Last Modified</th>
                                <th>Asset Count</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% with br as b %}
                                <tr>
                                    <td>
                                        <a href="{% url 'com:branch_detail' b.pk %}">{{b.id}}</a>
                                    </td>
                                    <td>{{ b.name }}</td>
                                    <td>
                                        {{b.created}} <br>
                                        <small class="text-muted">{{ b.created|naturaltime }}</small>
                                    </td>
                                    <td>
                                        {{b.modified}}
                                    </td>
                                    <td>
                                        {{b.computers.count}}
                                    </td>
                                </tr>
                            {% endwith %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="card-header">
                    {{ br.computers.count }} Computer Asset{{br.computers.count|pluralize}} at {{ br.name }}
                </div>
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>Asset ID</th>
                                <th>Nickname</th>
                                <th>Type</th>
                                <th>Logs Recorded</th>
                                <th>Location</th>
                                <th>Last modified</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for c in br.computers.all %}
                                <tr>
                                    <td>
                                        <a href="{% url 'com:computer' c.pk %}">{{c.id}}</a>
                                    </td>
                                    <td>{{ c.nickname }}</td>
                                    <td>{{ c.type }}</td>
                                    <td>{{c.logs.count }}</td>
                                    <td>
                                        Branch ID: {{ c.branch.id }} <br>
                                        <span class="text-muted">{{ c.branch.name }}</span>
                                    </td>
                                    <td>
                                        {{c.modified}} <br>
                                        <small class="text-muted">
                                            {{c.modified|naturaltime}}
                                        </small>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10" class="text-center">
                                        <i>Nothing available at the moment</i>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/branches.html
{% extends 'base.html' %}
{% load humanize %}
{% block branches_link_active %}active{% endblock %}
{% block page_header_title %}Branch List{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="card-header">
                    {{ brs.count }} Branches on File
                </div>
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>Branch ID</th>
                                <th>Name</th>
                                <th>Created On</th>
                                <th>Last Modified</th>
                                <th>Asset Count</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for b in brs %}
                                <tr>
                                    <td>
                                        <a href="{% url 'com:branch_detail' b.pk %}">{{b.id}}</a>
                                    </td>
                                    <td>{{ b.name }}</td>
                                    <td>
                                        {{b.created}} <br>
                                        <small class="text-muted">{{ b.created|naturaltime }}</small>
                                    </td>
                                    <td>
                                        {{b.modified}}
                                    </td>
                                    <td>
                                        {{b.computers.count}}
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10" class="text-center">
                                        <i>No logs available at the moment</i>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/comp.html
{% extends 'base.html' %}
{% load humanize %}
{% block assets_link_active %}active{% endblock %}
{% block page_header_title %}#{{comp.id}} &mdash; {{comp.nickname}}{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>Asset ID</th>
                                <th>Nickname</th>
                                <th>Type</th>
                                <th>Logs Recorded</th>
                                <th>Location</th>
                                <th>Last modified</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% with comp as c %}
                                <tr>
                                    <td>
                                        <a href="{% url 'com:computer' c.pk %}">{{c.id}}</a>
                                    </td>
                                    <td>{{ c.nickname }}</td>
                                    <td>{{ c.type }}</td>
                                    <td>{{c.logs.count }}</td>
                                    <td>
                                        Branch ID: {{ c.branch.id }} <br>
                                        <span class="text-muted">{{ c.branch.name }}</span>
                                    </td>
                                    <td>
                                        {{c.modified}} <br>
                                        <small class="text-muted">
                                            {{c.modified|naturaltime}}
                                        </small>
                                    </td>
                                </tr>
                            {% endwith %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row card-deck">
        <div class="card card-outline card-navy">
                <div class="card-header">
                    Event Share Metrics (On Device)
                </div>
                <div class="card-body">
                    <canvas id="boss-rep"></canvas>
                </div>
        </div>
        <div class="card card-outline card-navy">
                <div class="card-header">
                    Event Share Metrics (On Device) &mdash; Monthly
                </div>
                <div class="card-body">
                    <canvas id="mbb" style="height: 200px;"></canvas>
                </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        var pieChartCanvas = $('#boss-rep').get(0).getContext('2d');
        var pieData = {
                labels: [
                    {% for ev in events %}
                        '{{ ev.title }}',
                    {% endfor %}
                ],
                datasets: [
                    {
                    data: [
                        {% for ev in events %}
                            '{{ ev.logs.count }}',
                        {% endfor %}
                    ],
                    backgroundColor : [
                        {% for ev in events %}
                            '{{ ev.color }}',
                        {% endfor %}
                    ],
                    }
                ]
        }

        var pieOptions     = {
        maintainAspectRatio : false,
        responsive : true,
        }
        var pieChart = new Chart(pieChartCanvas, {
            type: 'pie',
            data: pieData,
            options: pieOptions      
        })
    </script>
{% endblock %}

templates/comps.html
{% extends 'base.html' %}
{% load humanize %}
{% block assets_link_active %}active{% endblock %}
{% block page_header_title %}Computer Assets Listing{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="card-header">
                    {{ comps.count }} Computer Asset{{comps.count|pluralize}}
                </div>
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>Asset ID</th>
                                <th>Nickname</th>
                                <th>Type</th>
                                <th>Logs Recorded</th>
                                <th>Location</th>
                                <th>Last modified</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for c in comps %}
                                <tr>
                                    <td>
                                        <a href="{% url 'com:computer' c.pk %}">{{c.id}}</a>
                                    </td>
                                    <td>{{ c.nickname }}</td>
                                    <td>{{ c.type }}</td>
                                    <td>{{c.logs.count }}</td>
                                    <td>
                                        Branch ID: {{ c.branch.id }} <br>
                                        <span class="text-muted">{{ c.branch.name }}</span>
                                    </td>
                                    <td>
                                        {{c.modified}} <br>
                                        <small class="text-muted">
                                            {{c.modified|naturaltime}}
                                        </small>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10" class="text-center">
                                        <i>Nothing available at the moment</i>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/cp.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block change_password_link_active %}active{% endblock %}
{% block page_header_title %} <i class="fas fa-key"></i> Change Password{% endblock page_header_title %}
{% block breadcrumbs %}
    <li class="breadcrumb-item active">
        Change Password
    </li>
{% endblock breadcrumbs %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-sm-12 col-md-4">
                                {{ form.old_password|as_crispy_field }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-sm-12 col-md-4">
                                {{ form.new_password1|as_crispy_field }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-sm-12 col-md-4">
                                {{ form.new_password2|as_crispy_field }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-sm-12 col-md-4">
                                <button class="btn btn-outline-primary btn-sm"><i class="fas fa-fingerprint"></i> Change Password </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock page_content %}

templates/events.html
{% extends 'base.html' %}
{% load humanize %}
{% block events_link_active %}active{% endblock %}
{% block page_header_title %}Events Reference{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="card-header">
                    {{ events.count }} Event{{events.count|pluralize}} Defined
                </div>
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>#</th>
                                <th>Code</th>
                                <th>Title</th>
                                <th>Color Code</th>
                                <th>Hits</th>
                                <th>Created on</th>
                                <th>Last modified</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for c in events %}
                                <tr>
                                    <td>
                                        <a href="{% url 'com:event' c.pk %}">{{c.id}}</a>
                                    </td>
                                    <td>{{ c.event_id }}</td>
                                    <td>{{ c.title }}</td>
                                    <td>{{c.color }} <br>
                                        <div style="width: 70px; height: 8px; background-color: {{ c.color }};"></div>
                                    </td>
                                    <td>
                                        {{c.logs.count}}
                                    </td>
                                    <td>
                                        {{c.created}} <br>
                                        <small class="text-muted">
                                            {{c.created|naturaltime}}
                                        </small>
                                    </td>
                                    <td>
                                        {{c.modified}} <br>
                                        <small class="text-muted">
                                            {{c.modified|naturaltime}}
                                        </small>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10" class="text-center">
                                        <i>Nothing available at the moment</i>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block home_link_active %}active{% endblock %}
{% block page_header_title %}Dashboard{% endblock page_header_title %}
{% block page_content %}
<div class="row">
    <div class="col-lg-4 col-6">
      <!-- small box -->
      <div class="small-box bg-secondary">
        <div class="inner">
          <h3>{{ asset_count }}</h3>

          <p>Computer Asset{{asset_count|pluralize }}</p>
        </div>
        <div class="icon">
          <i class="ion ion-bag"></i>
        </div>
        <a href="{% url 'com:computers' %}" class="small-box-footer">View All <i class="fas fa-arrow-circle-right"></i></a>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-4 col-6">
      <!-- small box -->
      <div class="small-box bg-success">
        <div class="inner">
          <h3>{{ branch_count }}</h3>

          <p>Branches on File</p>
        </div>
        <div class="icon">
          <i class="ion ion-stats-bars"></i>
        </div>
        <a href="{% url 'com:branches' %}" class="small-box-footer">View Branches <i class="fas fa-arrow-circle-right"></i></a>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-4 col-6">
      <!-- small box -->
      <div class="small-box bg-warning">
        <div class="inner">
          <h3>{{ log_count }}</h3>

          <p>Log{{log_count|pluralize}} Uploaded</p>
        </div>
        <div class="icon">
          <i class="ion ion-person-add"></i>
        </div>
        <a href="{% url 'com:logs' %}" class="small-box-footer">All Logs <i class="fas fa-arrow-circle-right"></i></a>
      </div>
    </div>
  </div>

  <div class="row">
      <div class="col-12">
          <div class="card card-outline card-navy">
            <div class="card-header">
                Recent Logs
            </div>
            <div class="table-responsive">
              <table class="table table-borderless mb-0">
                <thead class="bg-navy">
                    <tr>
                        <th>Entry ID</th>
                        <th>Processing Status</th>
                        <th>Branch</th>
                        <th>Computer</th>
                        <th>File</th>
                        <th>Logging Period</th>
                    </tr>
                </thead>
                <tbody>
                    {% for l in recent_logs %}
                        <tr>
                            <td>
                                <a href="{% url 'com:log_detail' l.pk %}">{{l.id}}</a>
                            </td>
                            <td>
                                {% if l.processed %}
                                <i class="fas fa-check-circle text-success"></i> Processed
                                {% else %}
                                    <i class="fas fa-times-circle text-muted"></i> Pending
                                {% endif %}
                            </td>
                            <td>
                                ID: {{ l.computer.branch.id }} <br>
                                <span class="text-muted">{{ l.computer.branch.name }}</span>
                            </td>
                            <td>
                                Serial: {{ l.computer.serial }} <br>
                                <span class="text-muted">{{l.computer.nickname }}</span>
                            </td>
                            <td>
                                <a href="{{ l.file.url }}">{{ l.file }}</a>
                            </td>
                            <td>
                                {{ l.start }} &mdash; {{l.end}} <br>
                                Duration:<span class="text-muted"> {{l.start|timesince:l.end }}</span>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="10" class="text-center">
                                <i>No logs available at the moment</i>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            </div>
          </div>
      </div>
  </div>
{% endblock %}

templates/log.html
{% extends 'base.html' %}
{% block logs_link_active %}active{% endblock %}
{% block page_header_title %}Log #{{log.id }}{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>Entry ID</th>
                                <th>Type</th>
                                <th>Branch</th>
                                <th>Computer</th>
                                <th>File</th>
                                <th>Logging Period</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% with log as l %}
                                <tr>
                                    <td>
                                        <a href="{% url 'com:log_detail' l.pk %}">{{l.id}}</a>
                                    </td>
                                    <td>{{ l.type }}</td>
                                    <td>
                                        ID: {{ l.computer.branch.id }} <br>
                                        <span class="text-muted">{{ l.computer.branch.name }}</span>
                                    </td>
                                    <td>
                                        Serial: {{ l.computer.serial }} <br>
                                        <span class="text-muted">{{l.computer.nickname }}</span>
                                    </td>
                                    <td>
                                        <a href="{{ i.file.url }}">{{ l.file }}</a>
                                    </td>
                                    <td>
                                        {{ l.date_from }} &mdash; {{l.date_to}} <br>
                                        Duration:<span class="text-muted"> {{l.date_from|timesince:l.date_to }}</span>
                                    </td>
                                </tr>
                            {% endwith %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/logs.html
{% extends 'base.html' %}
{% block logs_link_active %}active{% endblock %}
{% block page_header_title %}Log List{% endblock page_header_title %}
{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-navy">
                <div class="card-header">
                    {{ logs.count }} Log{{logs.count|pluralize}} Uploaded
                </div>
                <div class="table-responsive">
                    <table class="table table-borderless mb-0">
                        <thead class="bg-navy">
                            <tr>
                                <th>Entry ID</th>
                                <th>Processing Status</th>
                                <th>Branch</th>
                                <th>Computer</th>
                                <th>File</th>
                                <th>Logging Period</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for l in logs %}
                                <tr>
                                    <td>
                                        <a href="{% url 'com:log_detail' l.pk %}">{{l.id}}</a>
                                    </td>
                                    <td>
                                        {% if l.processed %}
                                        <i class="fas fa-check-circle text-success"></i> Processed
                                        {% else %}
                                            <i class="fas fa-times-circle text-muted"></i> Pending
                                        {% endif %}
                                    </td>
                                    <td>
                                        ID: {{ l.computer.branch.id }} <br>
                                        <span class="text-muted">{{ l.computer.branch.name }}</span>
                                    </td>
                                    <td>
                                        Serial: {{ l.computer.serial }} <br>
                                        <span class="text-muted">{{l.computer.nickname }}</span>
                                    </td>
                                    <td>
                                        <a href="{{ l.file.url }}">{{ l.file }}</a>
                                    </td>
                                    <td>
                                        {{ l.start }} &mdash; {{l.end}} <br>
                                        Duration:<span class="text-muted"> {{l.start|timesince:l.end }}</span>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10" class="text-center">
                                        <i>No logs available at the moment</i>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}